version: '3.9'

services:
  workout-web-app:
    build: .
    container_name: workout-web-app
    ports:
      - "5000:5000"
    volumes:
      - ./workouts.db:/app/workouts.db
    restart: unless-stopped
